# Usa una imagen oficial y ligera de Nginx basada en Alpine Linux
FROM nginx:alpine

# Copia el archivo index.html dentro de la carpeta donde Nginx busca la web
COPY index.html /usr/share/nginx/html/

# Expone el puerto 80 para poder acceder a la aplicación
EXPOSE 80
